### ISSUE TITLE
Replace proprietary assets to create a free version of the game

### ISSUE THREAD

**Issue by davcri** [crystal-bit/triple-triad-godot#6]
It would be nice to replace all the proprietary assets (textures, sprite fonts and sounds) so that I can release the game without too many problems.

At the moment this is not a priority, but if a multiplayer mode will be implemented, I will prioritize this issue (so that it could be played and distributed freely).

## Todo

- [ ] Write some docs on how to replace existing assets
- [ ] (maybe) Create an integrated editor
- [ ] Find at least 10 free cards textures
- [ ] Find free background mat texture
- [ ] Find free music background
- [ ] Find free sounds for "selection" and "denied"

**Comment by Hairic95** [comment]
I may draw some pixel art sprite for the cards, however it may took a while for me to free me up to make them. Will the drawings require to be on the final fantasy characters?

**Comment by davcri** [comment]
Hi Hairic! Thank you very much for showing up so quickly, I appreciate it :smile:   
The arts should be unrelated to Final Fantasy, so that we can distribute it to other people without copyright issues. However I think that we can safely "take inspiration" from FF, in the same way as [Tuxemon project](https://www.tuxemon.org/) did with Pokemon.

Take all the time that you need and feel free to post updates here.

**Comment by davcri** [comment]
A fork has  been created some time ago, so this issue is not relevant anymore.

https://github.com/crystal-bit/trium-vis

Currently I think that it will be easier to just complete the original remake, polish it and only then focusing on a 100% open source release.
